[package]
name = "accumulator_auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4.4"
num-primes = "0.3.0"
rand = "0.8.5"
rug = "1.22.0"
serde_json = "1.0.107"
sha2 = "0.10.7"
